import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#f3f3f3',
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 24,
    backgroundColor: '#f3f3f3',
  },
  headerRow: {
    width: '100%',
    alignItems: 'flex-start',
    marginBottom: 18,
  },
  homeBadge: {
    width: 42,
    height: 42,
    borderRadius: 14,
    backgroundColor: '#f3f3f3',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
  },
  headerTextWrap: {
    width: '100%',
  },
  title: {
    fontSize: 34,
    fontWeight: '700',
    lineHeight: 38,
    color: '#111111',
    textAlign: 'left',
  },
  subtitle: {
    marginTop: 8,
    fontSize: 18,
    fontWeight: '500',
    color: '#111111',
  },
  grid: {
    width: '100%',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginTop: 12,
    marginBottom: 24,
  },
  card: {
    width: '46%',
    minHeight: 160,
    backgroundColor: '#f9f9f9',
    borderRadius: 26,
    paddingVertical: 18,
    paddingHorizontal: 16,
    marginBottom: 18,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
  },
  deviceIconContainer: {
    width: 62,
    height: 62,
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  lightAccent: {
    backgroundColor: '#f0f0f0',
  },
  darkAccent: {
    backgroundColor: '#efefef',
  },
  deviceName: {
    fontSize: 18,
    fontWeight: '600',
    color: '#111111',
    marginBottom: 4,
  },
  deviceStatus: {
    fontSize: 14,
    fontWeight: '700',
    letterSpacing: 0.5,
    color: '#111111',
  },
  primaryButton: {
    width: '100%',
    backgroundColor: '#111111',
    borderRadius: 18,
    paddingVertical: 16,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
});